// Generated by CoffeeScript 1.7.1
(function() {
  var Game;

  Game = (function() {
    Game.prototype.level = 1;

    function Game() {
      var aspectRatio, controls, cube, dim, size;
      this.renderer = new Renderer().t();
      this.scene = new THREE.Scene();
      aspectRatio = Window.aspectRatio();
      size = 900;
      this.camera = new THREE.OrthographicCamera(-aspectRatio * size / 2, aspectRatio * size / 2, size / 2, -size / 2, -1000, 1000);
      dim = new Dimension(100, 100, 100);
      cube = new Cube(dim);
      this.scene.add(cube.t());
      cube = new Cube(dim, new Position(100, 0, 0));
      this.scene.add(cube.t());
      this.camera.rotation.x = -0.1;
      this.camera.rotation.y = 0.8;
      controls = new THREE.OrbitControls(this.camera, this.renderer.domElement);
      this.render();
    }

    Game.prototype.render = function() {
      return this.renderer.render(this.scene, this.camera);
    };

    return Game;

  })();

}).call(this);
