// Generated by CoffeeScript 1.7.1
(function() {
  window.Floor = (function() {
    function Floor() {
      var face, geometry, i, l, material, _i, _ref;
      geometry = new THREE.PlaneGeometry(2000, 2000, 100, 100);
      geometry.applyMatrix(new THREE.Matrix4().makeRotationX(-Math.PI / 2));
      l = geometry.faces.length;
      for (i = _i = 0, _ref = l - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        face = geometry.faces[i];
        face.vertexColors[0] = new THREE.Color();
        face.vertexColors[1] = new THREE.Color();
        face.vertexColors[2] = new THREE.Color().setHSL(0.1, 0.4, 0.2);
      }
      material = new THREE.MeshBasicMaterial({
        vertexColors: THREE.VertexColors
      });
      this.mesh = new THREE.Mesh(geometry, material);
    }

    return Floor;

  })();

}).call(this);
