// Generated by CoffeeScript 1.7.1
(function() {
  var Renderer;

  Renderer = (function() {
    function Renderer() {
      this.renderer = new THREE.WebGLRenderer();
      this.renderer.setSize(Window.w(), Window.h());
      document.body.appendChild(this.renderer.domElement);
    }

    Renderer.prototype.rendererClass = function() {
      if (Window.webGL()) {
        return THREE.WebGLRenderer;
      } else {
        return THREE.CanvasRenderer;
      }
    };

    Renderer.prototype.t = function() {
      return this.renderer;
    };

    return Renderer;

  })();

}).call(this);
