// Generated by CoffeeScript 1.7.1
(function() {
  var Window;

  Window = (function() {
    function Window() {}

    Window.aspectRatio = function() {
      return this.w() / this.h();
    };

    Window.webGL = function() {
      return !!window.WebGLRenderingContext;
    };

    Window.w = function() {
      return window.innerWidth;
    };

    Window.h = function() {
      return window.innerHeight;
    };

    return Window;

  })();

}).call(this);
