CUBE_SIZE 	 = 50
BLOCK_HEIGHT = 4  * CUBE_SIZE
BLOCK_WIDTH  = 3  * CUBE_SIZE

GRID_WIDTH_IN_CUBES  = 9
GRID_HEIGHT_IN_CUBES = 16

GRID_WIDTH  = CUBE_SIZE * GRID_WIDTH_IN_CUBES
GRID_HEIGHT = CUBE_SIZE * GRID_HEIGHT_IN_CUBES

TOP    = GRID_HEIGHT
LEFT   = 0
BOTTOM = 0
RIGHT  = GRID_WIDTH
CENTER = GRID_WIDTH / 2
